import "./globals.css";
import { Open_Sans } from "next/font/google";

const inter = Open_Sans({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={
          inter.className +
          " flex justify-center h-screen bg-cover md:bg-[url(/images/bg-mobile.svg)] bg-[url(/images/bg-desktop.svg)] bg-Violet"
        }
      >
        {children}
      </body>
    </html>
  );
}
